#!/bin/bash

USER1_NAME="user1"
USER1_EMAIL="user1@user1.com"
USER2_NAME="user2"
USER2_EMAIL="user2@user2.com"

ARGS=(
u1
u2
list
)

function user1()
{
    git config --global user.name $USER1_NAME
    git config --global user.email $USER1_EMAIL
    echo "Current setting:"
    git config -l | grep user
}

function user2()
{
    git config --global user.name $USER2_NAME
    git config --global user.email $USER2_EMAIL
    echo "Current setting:"
    git config -l | grep user
}

function list()
{
    echo "user1.name=$USER1_NAME"
    echo "user1.email=$USER1_EMAIL"
    echo "user2.name=$USER2_NAME"
    echo "user2.email=$USER2_EMAIL"
}

function gitsw()
{
    if [ $# == 1 ]; then
        case $1 in
            ${ARGS[0]})
                user1
                ;;
            ${ARGS[1]})
                user2
                ;;
            ${ARGS[2]})
                list
                ;;
        esac
    else
        echo "Usage: my_vpn {${ARGS[@]}}"
        echo ""
        echo "Current setting:"
        git config -l | grep user
        return 0
    fi
}

# auto complete for tab
function _gitsw()
{
    local cur
    COMPREPLY=()
    cur=${COMP_WORDS[COMP_CWORD]}

    case "$cur" in
        *)
            COMPREPLY=( $( compgen -W '${ARGS[@]}' -- $cur ) )
            ;;
    esac
}

gitsw $1

complete -F _gitsw -o filenames gitsw
